name: CI tests for most supported db drivers

on:
  push:
    tags:
      - "!no-engines"
    branches:
      - "!no-engines"
  pull_request:

env:
    ORACLE_Skip: 0
    ORACLE_Host: localhost
    ORACLE_Port: 1521
    ORACLE_SSL: 0
    ORACLE_UsernameSys: sys
    ORACLE_PasswordSys: Oradoc_db1
    ORACLE_Database: orclpdb1.localdomain
    ORACLE_Username: typeorm_mg
    ORACLE_Password: Passw0rd

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:

    - name: Login to registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup containers
      run: docker-compose up -d oracle oracle_client

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm t
